import "./assets/css/reset.css";
import "./assets/css/globals.css";
import "./assets/css/colors.css";

import Header from "@/components/header";
import { initializeApp } from "firebase/app";
const firebaseConfig = {

  apiKey: "AIzaSyCYAtyxKyA7Hh4fwQ8h_cHSO1CrQ5R1gZ8",

  authDomain: "job-board-34db1.firebaseapp.com",

  databaseURL: "https://job-board-34db1-default-rtdb.firebaseio.com",

  projectId: "job-board-34db1",

  storageBucket: "job-board-34db1.appspot.com",

  messagingSenderId: "1027206871342",

  appId: "1:1027206871342:web:aa5f2caae82ca6b4d6a2bf",

  measurementId: "G-9PT3EEC744"

};

const app = initializeApp(firebaseConfig);
// const analytics = getAnalytics(app);

export const metadata = {
  title: "job board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="main">
          <div className="container">{children}</div>
        </main>
      </body>
    </html>
  );
}

