import "./assets/css/reset.css";
import "./assets/css/globals.css";
import "./assets/css/colors.css";

import Header from "@/components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="main">
          <div className="container">{children}</div>
        </main>
      </body>
    </html>
  );
}
